### ISSUE TITLE
lcnn.box.BoxKeyError error while training

### ISSUE THREAD

**Issue by velutis** [zhou13/lcnn#15]
Hi,  i try to train this model how described in manual, but i am getting error 
cnn.box.BoxKeyError: "\'Box\' object has no attribute \'image\'"\n'
i use the pre-processed dataset wireframe.tar.xz from google drive. Any hints how ti fix this? Thanks

**Comment by zhou13** [comment]
Do you properly specify the config file?

**Comment by velutis** [comment]
i use default original config checked out from github config/wireframe.yaml
my command is line in manual: python ./train.py -d 0 --identifier baseline  config/wireframe.yaml

**Comment by zhou13** [comment]
Does `cat config/wireframe.yaml` output anything?

**Comment by velutis** [comment]
yes of course:)
```
io:

  logdir: logs/
  datadir: data/wireframe/
  resume_from:
  num_workers: 4
  tensorboard_port: 0
  validation_interval: 24000

model:
  image:
      mean: [109.730, 103.832, 98.681]
      stddev: [22.275, 22.124, 23.229]

  batch_size: 6

  # backbone multi-task parameters
  head_size: [[2], [1], [2]]
  loss_weight:
    jmap: 8.0
    lmap: 0.5
    joff: 0.25
    lpos: 1
    lneg: 1

  # backbone parameters
  backbone: stacked_hourglass
  depth: 4
  num_stacks: 2
  num_blocks: 1

  # sampler parameters
  ## static sampler
  n_stc_posl: 300
  n_stc_negl: 40

  ## dynamic sampler
  n_dyn_junc: 300
  n_dyn_posl: 300
  n_dyn_negl: 80
  n_dyn_othr: 600

  # LOIPool layer parameters
  n_pts0: 32
  n_pts1: 8

  # line verification network parameters
  dim_loi: 128
  dim_fc: 1024

  # maximum junction and line outputs
  n_out_junc: 250
  n_out_line: 2500

  # additional ablation study parameters
  use_cood: 0
  use_slop: 0
  use_conv: 0

  # junction threashold for evaluation (See #5)
  eval_junc_thres: 0.008

optim:
  name: Adam
  lr: 4.0e-4
  amsgrad: True
  weight_decay: 1.0e-4
  max_epoch: 24
  lr_decay_epoch: 10
```
